services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
          "-e",
          "SELECT 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    volumes:
      - ./fastapi/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port ${FASTAPI_PORT} --reload
    env_file:
      - .env

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    container_name: nextjs
    restart: unless-stopped
    ports:
      - "${NEXTJS_PORT}:${NEXTJS_PORT}"
    volumes:
      - ./nextjs:/app
    command: npm run dev
    env_file:
      - .env

volumes:
  mysql-data:
